### ISSUE TITLE
Redownload Media not removing thumb and nfo

### ISSUE THREAD

**Issue by itmunky** [meeb/tubesync#83] opened 2021-03-01 12:38 UTC
When using the "Really delete and redownload media" function the video / audio file is deleted however the associated thumb (.jpg) and NFO (.nfo) remain in the download folder. 

I noticed this after changing the media format (naming) option wanting to remove old files and re-download as new media format (naming format).

**Comment by meeb** [comment] 2021-03-02 00:23
TubeSync does actually delete the NFO files and thumbnails, however I would suspect this is a duplicate of #67 - the NFO likely was written with the wrong file name which is why it was not removed. Could you confirm please?

**Closed** 2022-04-06 06:25 UTC
Labels: question
