### ISSUE TITLE
Files re-download immediately after deleting

### ISSUE THREAD

**Issue by efirestone** [meeb/tubesync#178] opened 2021-10-18 21:04 UTC
Reproduction Steps:
- Add a new channel
- While the videos for the channel are initially downloading, go in and mark some of them as "skipped"
- The videos will download anyway
- If you (again) go in and try to Delete/Mark as Skipped on those files they will immediately re-download
- Files that weren't marked as skipped during the initial download process delete just fine (and don't re-download)

There seems to be some race condition with marking items as skipped while they're in the initial downloading phase.

**Comment by meeb** [comment] 2021-10-19 03:09
Yeah there's a logic bug where some of the "can download" checks auto-unskips a skipped media item in some cases. This is a dupe of #119 - thanks for the report though it's on the list.

**Closed as completed by meeb** 2021-10-19 03:09 UTC
