### ISSUE TITLE
Thumbnail directory

### ISSUE THREAD

**Issue by talkingseedling** [meeb/tubesync#311] opened 2023-01-20 03:32 UTC
Thumbnail and NFO files don't exactly follow the naming convention set by [MEDIA FORMAT]
I set Media Format to: Season {yyyy}/{source_full} - {yyyy}x{mm}{dd} - {title_full}.{ext}
The video files successfully follow this convention, but the thumbnail and NFO files do not, ignoring everything before the "/".

Video files take on /downloads/video/[DIRECTORY]/Season {yyyy}/{source_full} - {yyyy}x{mm}{dd} - {title_full}.{ext}
Thumbnails and NFO take on /downloads/video/[DIRECTORY]/{source_full} - {yyyy}x{mm}{dd} - {title_full}.{ext}

Video files are successfully getting added to a subfolder sorted by year (doing this for better Jellyfin support), but the thumbnails and NFO files all pile up together in the parent directory.

Version 0.12.0

**Comment by meeb** [comment] 2023-01-20 09:22
Thanks for the issue. Is this a duplicate of #294 ?

**Comment by talkingseedling** [comment] 2023-01-20 11:04
Ahh yes, sorry I did look for duplicates but clearly not well enough.

**Comment by meeb** [comment] 2023-01-20 11:44
No problem. I'll close this one. You can track the future fix in the other issue.

**Closed by meeb** 2023-01-20 11:44 UTC
