### ISSUE TITLE
Channel source URL modification

### ISSUE THREAD

**Issue by talkingseedling** [meeb/tubesync#396] opened 2023-07-28 04:10 UTC
Just added a channel that doesn't work. It seems when you add a channel to tubesync, it gets the channel name after the @, and prepends https://www.youtube.com/c/. So even if you paste in say https://www.youtube.com/@TheKneesovertoesguy, tubesync rewrites the URL to be https://www.youtube.com/c/@TheKneesovertoesguy. This has been fine for most channels I've added, but I found one where youtube doesn't resolve with the added /c/. https://www.youtube.com/@spanishafterhours is a channel that exists, but https://www.youtube.com/c/@spanishafterhours as a URL does not resolve, so it can't be added to tubesync.

Proposed solutions (from a non-programmer) that either the channel URL used by tubesync is copied directly from the user input field, or the /c/ is dropped as the channel URLs seem to resolve fine without them.

**Comment by meeb** [comment] 2023-07-28 04:48
The issue here is that @youtube_username channels aren't actually channels in many cases, but user overview pages or collections of playlists or other groups of videos. Sometimes the @youtube_username syntax works (the `/videos` URL postfix works) and sometimes it doesn't. This is discussed at length in previous issues (#243, #299 etc.).  The /c/ prefix check is by design to test if it's an actual channel or not as a hack.

There was some work to automatically attempt to detect this, but by the time I got it working YouTube had changed it again (from /user/ to @) and I've not revisited it since.

In the mean time, you can translate the @youtube_username channels that don't work to their actual real channel IDs and use those.

For example the actual channel ID for https://www.youtube.com/@TheKneesovertoesguy is https://www.youtube.com/channel/UCGybO-bWZ3W6URh42sdMQiw so you can add a channel by ID and enter UCGybO-bWZ3W6URh42sdMQiw which will work.

The channel ID for @spanishafterhours  is UCfG2VhlQgy5bHGmkpeKcjVA.

This could absolutely be improved, but it needs lots of auto-detection and rewriting of the "add channel" feature to work so just use the channel IDs for now.

**Comment by talkingseedling** [comment] 2023-07-28 04:59
Thanks as always for the fast reply. Works great.

For others who find this, you can find channel ID by viewing the channel page source and searching `channel_id=`

**Comment by meeb** [comment] 2023-07-28 07:50
No problem, and thanks for the note for others. You OK if I close this issue?

**Comment by talkingseedling** [comment] 2023-07-28 07:53
No worries

**Comment by instantdreams** [comment] 2023-08-02 22:59
This was an issue for me. I found the Stream Weasels had a [username, handle, or legacy](https://www.streamweasels.com/tools/youtube-channel-id-and-user-id-convertor/) converter. This has so far worked well with TubeSync.

**Comment by MatthK** [comment] 2023-08-11 10:33
How do you translate the channel name @name to the ID? Where or how do I find the channel ID?

**Comment by talkingseedling** [comment] 2023-08-11 11:12
> How do you translate the channel name @name to the ID? Where or how do I find the channel ID?

The comment directly above yours has a link on how to do it.

**Closed** 2023-08-11 11:12 UTC
