### ISSUE TITLE
Feature Request: Configurable default settings

### ISSUE THREAD

**Issue by LonlyGamerX** [meeb/tubesync#543] opened 2024-10-06 07:30 UTC
I would like to propose a feature enhancement regarding the configuration of default values on the site. Currently, it requires manual adjustments each time a new source is added.

I suggest introducing a “Settings” tab on the site where users can modify the default values for all settings related to adding new sources. For example, if I consistently set the Media Format to {title_full}.{ext} every time I add a new source, it would be beneficial to have this as a preset option rather than needing to edit it manually each time.

**Comment by meeb** [comment] 2024-10-06 10:37
Hi, thanks for the issue. Is this a dupe of #28 ?

**Comment by LonlyGamerX** [comment] 2024-10-06 13:54
hey sorry, did not see this had already been brought up

**Comment by meeb** [comment] 2024-10-07 00:57
Not a problem. There are a lot of issues so finding dupes isn't the simplest task.

**Closed by meeb** 2024-10-07 00:57 UTC
