### ISSUE TITLE
Allow --write-info-json so downloads can work with emby

### ISSUE THREAD

**Issue by retrospectvideo** [meeb/tubesync#78] opened 2021-02-25 06:43 UTC
Allow --write-info-json so downloads can work with emby, currently does not read any of the metadata for downloaded channels.

**Comment by meeb** [comment] 2021-02-25 08:10
Sure I can look into this, sounds reasonable to add as an extra metadata file option.

**Comment by retrospectvideo** [comment] 2021-02-25 08:12
actually here is the issue with emby. the nfo file has to match the video filename. the filename for nfo file does not work. I fixed it simply by changing the filename.

**Comment by meeb** [comment] 2021-02-25 08:14
Ah perfect. Is this actually just a dupe of #67 then?

**Comment by retrospectvideo** [comment] 2021-02-25 08:16
thats right good call.

**Comment by meeb** [comment] 2021-02-25 08:17
Nice, thanks for the confirmation. I'll close this as a dupe for now.

**Closed by meeb** 2021-02-25 08:17 UTC
Labels: duplicate
