### ISSUE TITLE
Live stream marked as failed

### ISSUE THREAD

**Issue by UniverseXXX** [meeb/tubesync#226] opened 2022-03-27 19:02 UTC
Live stream marked as failed (Media cannot be downloaded because it has no formats which match the source requirements) and being ignored(not downloading) when stream finished and uploaded.

If scheduled task doesn't run during live stream then it successfully process and download.

**Comment by meeb** [comment] 2022-03-27 22:56
That makes sense given `yt-dlp` won't download the video until it's available as a VOD after the live stream. The retry should work though given it'll retry the download for quite a long time after the stream has finished. What YouTube URL is this livestream on?

**Comment by UniverseXXX** [comment] 2022-03-28 07:52
Here is the [link](https://www.youtube.com/c/G1deon)
Please let me know if you need further details. Thanks for looking into this.

**Comment by meeb** [comment] 2022-03-28 07:57
That's the channel - can you tell me specifically which video failed to download on that channel?

**Comment by UniverseXXX** [comment] 2022-03-28 07:58
Sry, https://www.youtube.com/watch?v=TBHSS0Gsi2M

**Comment by meeb** [comment] 2022-03-28 08:01
That looks like it should now download as I assume YouTube has had enough time to process it to a VOD. Can you skip then unskip the media in TubeSync and see if that makes it download?

**Comment by UniverseXXX** [comment] 2022-03-28 08:08
I have skipped it, but it still appears in the main list. So I cannot unskip it.

![image](https://user-images.githubusercontent.com/7465472/160354262-c164f1c2-8226-460d-a858-1743c2a1d974.jpeg)

![image](https://user-images.githubusercontent.com/7465472/160354448-1df0c0f3-a999-4279-8ff0-c03b6e25ff0c.jpeg)

**Comment by meeb** [comment] 2022-03-28 08:17
I've just pushed a minor patch which should help. Please wait 10-15 mins then update your container to `:latest`. When you use the "really delete and skip media" button (after updating) and then unskip the media it will now redownload fresh metadata, which should trigger your download to start. The issue is the existing metadata stored for the media has no duration as it was a live stream. The updated metadata once the stream becomes a VOD does have a duration, so in theory refreshing the metadata will resolve this.

**Comment by UniverseXXX** [comment] 2022-03-28 08:51
Thanks @meeb this has now fixed. Do I need manually skip media for every failed download in the future or script will do it automatically for every video with zero length?

**Comment by meeb** [comment] 2022-03-28 08:53
Good to hear that fixed it for you. For now, yes you'll need to manually delete and unskip any zero length media items. I'll add a task to watch for these to automatically retry their metadata. That'll be a different issue though so I'll close this one for now. Feel free to comment back here if you encounter any follow-up problems.

**Closed by meeb** 2022-03-28 08:53 UTC

**Comment by BenJamesAndo** [comment] 2023-04-05 00:43
> That'll be a different issue though so I'll close this one for now. Feel free to comment back here if you encounter any follow-up problems.


Is there a link to the different issue, or rather has any progress been made on this? I'm keen for some sort of automatic way to do this.
