### ISSUE TITLE
Change defaults settings for adding a channel/playlist

### ISSUE THREAD

**Issue by kanjieater** [meeb/tubesync#526] opened 2024-07-26 19:25 UTC
![image](https://github.com/user-attachments/assets/4e122035-d6f2-425e-b0d7-0ab85dbef13e)
I'd like to templatize the settings that I have here. I had to adjust quite a few of them, but every time I add a channel I have to recheck/uncheck all of what I would consider to be a personal default for adding channels.

**Comment by meeb** [comment] 2024-07-27 06:09
Hi, is this a dupe of #28 ?

**Comment by kanjieater** [comment] 2024-07-27 13:32
I believe it is. I'm using docker, so the workaround relating to changing the defaults in models.py won't work. Do you have any other ways to workaround this?

**Closed** 2024-07-27 13:32 UTC

**Comment by meeb** [comment] 2024-07-28 05:17
There currently isn't a sane way to have defaults at the moment, sorry. It's probably getting closer to being next on the list to add as a feature though.
