### ISSUE TITLE
Uploaded Timestamp in File Name?

### ISSUE THREAD

**Issue by zpz5HAU-tgc3fgw2xwr** [meeb/tubesync#166] opened 2021-10-02 16:53 UTC
Is there any info available to you that would allow you to add an uploaded timestamp to the file name? If there was a way to add a timestamp, I'm thinking that would allow a more accurate sorting in Plex (similar to your subscriptions feed on YouTube).

Currently I'm adding `{yyyy_mm_dd}` to the beginning of the file name, which results in it being mostly correct in the Plex UI as far as sorting by most recent goes.

Because this would increase the size of the filename, and that would make it look bad in the Plex UI, I'd probably just use the hour and maybe the minute. So maybe something like `{yyyy_mm_dd} {HH}` `{yyyy_mm_dd} {HH:mm}`

**Comment by meeb** [comment] 2021-10-03 03:13
Sure I can add a hour and minute macro to the file path templates. The date stamp contains the seconds so the information is already there.

**Comment by meeb** [comment] 2021-10-15 09:51
Just noticed this is a dupe of #133 so I'll close it for now.

**Closed as completed by meeb** 2021-10-15 09:51 UTC
