### ISSUE TITLE
Youtube Channel errors when being indexed

### ISSUE THREAD

**Issue by sofasogud** [meeb/tubesync#32] opened 2021-01-02 19:09 UTC
Hey! Thanks for this great app! I got things working with a few sources and everything was working fine but now it's coming up with the below error for each source.

Index media from source "Youtube Channel", attempted 2 times
Error: "Youtube Channel" (ID: 'ChannelID') returned no media to index, is the source key valid? Check the source configuration is correct and that the source is reachable"

<img width="1171" alt="Screenshot 2021-01-02 at 19 09 32" src="https://user-images.githubusercontent.com/40215388/103464751-0e60ee80-4d2e-11eb-80a9-387f7636f128.png">

**Comment by meeb** [comment] 2021-01-03 01:51
That ID looks a bit mangled, can you paste the original YouTube URL you added as a source?

**Comment by sofasogud** [comment] 2021-01-03 09:53
Here the original I added. This source is working now and was working previously.

https://www.youtube.com/channel/UC9OIwUcx-Uss7xj7s1P5XGw

I actually and went through and deleted all the sources that hadn’t yet downloaded any media then reset tasks and then the errors disappeared. 

I’m going through and slowly adding each source to see if there is one that is causing the errors for everything or maybe it’s because I added about 10 additional sources in one go?

I’ll let you know what happens.

**Comment by meeb** [comment] 2021-01-03 09:59
Sure, update the issue if you find out more. Internally, TubeSync just passes the URL to `youtube-dl` which attempts to index the videos on the channel. If `youtube-dl` finds no videos, it raises that error as it could mean either an empty channel or it could mean the channel name was invalid.

This could also be caused by things like:
* Your TubeSync being unable to connect to YouTube
* YouTube blocking your connections somehow
* Any other reason that would make the requests to YouTube fail and return no videos

So, it's a pretty broad "it's not working right now but we're not sure why" error, which is why it retries the indexing several times before marking the source as error'd. You can check more specific logs with `docker logs [container name]` on the shell of the server you're running the container from as the top level error isn't that descriptive. You'll only really find the exact error from the console logs probably.

**Comment by Catsrules** [comment] 2021-02-01 04:48
I believe I might have had a similar issue. I setup TubeSync about a month ago setup some random channels and then life got in the way and I just let it do its thing and didn't check on it. Today I happened to have some time to take a look at it again but all of my sources were saying the source key is invalid. If I deleted them and readded the channels it would work fine. 

Some are using the channel ID and some are using the channel Name.  I know they are both correct and should be working. 

I figure maybe an update would help so I update from v0.7 to v0.8 still had the same problem. However after I updated I notice that I didn't have any tasks assigned to any of my channels. not sure if this was also the case with .7 as I only notices after I updated. (I suspect the tasks were also missing from v0.7but again I can't be sure.

Anyways after I notice the lack of tasks I reset the task (using the reset task button on the bottom of the task page) and everything started working again. 

Recently my house has had a few power outages and internet outages so Tubesync has been ungracefully shutdown multiple times as well as no internet. Not sure if that is the cause of some of my issues. 

Unfortunately my logs got erased in the upgrade and I don't see any errors or issues in my existing logs. So I am not going to be much help in the regard. Just thought it might help.

**Comment by meeb** [comment] 2021-02-01 05:09
Thanks for the additional feedback. Hopefully this will get fixed with some additional checks in the next release when I get a chance to look at the tickets. The "reset tasks" button does exist pretty much because I noticed it was randomly twitchy during early testing so I'm not too surprised people have encountered similar issues.

**Comment by Catsrules** [comment] 2021-02-01 05:25
> 
> 
> Thanks for the additional feedback. Hopefully this will get fixed with some additional checks in the next release when I get a chance to look at the tickets. The "reset tasks" button does exist pretty much because I noticed it was randomly twitchy during early testing so I'm not too surprised people have encountered similar issues. If you get some errors in the logs over time in the console please add them to this ticket.

Well do. Thanks for such a cool program.

**Comment by meeb** [comment] 2021-02-18 05:42
This has been bundled into a larger refactoring of how tasks and background work is triggered and processed (e.g. #40 ) - I'll close this issue for now as the major refactoring work should resolve these issues as a by-product in future work. Please feel free to follow #40 for updates.

**Closed by meeb** 2021-02-18 05:42 UTC
