### ISSUE TITLE
Feature Request:  Add youtube 'Channel Name' to media name variables

### ISSUE THREAD

**Issue by bryanhoffman04** [meeb/tubesync#417] opened 2023-10-10 20:55 UTC
That way you could name files: 'channel name - title'

Thanks!

**Comment by meeb** [comment] 2023-10-11 11:54
Duplicate of #270 ?

**Comment by bryanhoffman04** [comment] 2023-10-11 14:56
Yes, my mistake.

**Comment by meeb** [comment] 2023-10-12 03:59
No problem!

**Closed by meeb** 2023-10-12 03:59 UTC
