### ISSUE TITLE
Changing source settings does not modify existing files

### ISSUE THREAD

**Issue by Adrian-at-CrimsonAuzre** [meeb/tubesync#25] opened 2020-12-21 18:41 UTC
For example, if I check "Copy thumbnails" _after_ I did the initial save and download it should probably download them either right away or on the next scan. Same with changing the name format or directory.

**Comment by meeb** [comment] 2020-12-22 01:07
Yes, this is by design / as expected. Changes to source settings do not retroactively change existing media. Logically, this makes more sense than some changes being applied and others not. For example, changing the desired resolution from 720p to 1080p doesn't trigger re-downloading all of your existing videos which wouldn't be that obvious a by-product of your saving the source details.

There's a "sync metadata" separate command on the roadmap which will delete or create NFO/thumbnails as per your current source settings which will probably make it into the next release. This will likely need to be manually triggered though rather than automatically triggered on source save.

**Comment by Adrian-at-CrimsonAuzre** [comment] 2020-12-22 01:19
That would work too.

**Comment by meeb** [comment] 2021-02-18 06:24
Pushed into `:latest` and will be in `v0.9` this new custom command should do what you want. Docs here:

https://github.com/meeb/tubesync/blob/main/docs/create-missing-metadata.md

**Closed** 2021-02-18 06:24 UTC
